### ISSUE TITLE
consider making IsDarkMode static

### ISSUE THREAD

**Issue by MagicAndre1981** [BlueMystical/Dark-Mode-Forms#26]
I try to do checks for Light/Dark Mode in Program.cs before I created a window, here I need to access the IsDarkMode property, but this is not possible without creating an instance of DarkModeCS.

Is it possible to make it static to allow using it without any instance?

**Comment by kachnitata** [comment]
I agree, and suggest the same for the whole section "Public Members".

I was already wondering earlier, where there was any particular reason for creating a new instance of DarkModeCS for each form, and I think there is not...

**Comment by BlueMystical** [comment]
Creating an instance is required because it starts the events listening for changes in the Controls, who are associated to a Window handle.
You can however, use the `GetWindowsColorMode()` method instead, who is already Static and will return the User's chose Color mode:
![image](https://github.com/BlueMystical/Dark-Mode-Forms/assets/10116951/7df1322b-b849-48cb-bcc4-d2dd833f4f8a)

**Comment by MagicAndre1981** [comment]
ok, this works, thanks.
