### ISSUE TITLE
Feature Request: Add Debug Option to force a theme

### ISSUE THREAD

**Issue by MagicAndre1981** [BlueMystical/Dark-Mode-Forms#30]
It would be nice to have a debug option to force a theme (Light/dark) without having to change it in the windows settings app.

Is this possible to add or too complicated?

**Comment by kachnitata** [comment]
A colleague asked me about the same today....

**Comment by BlueMystical** [comment]
it would be nice but the problem is the whole Window Title area and Borders, those are gotten from the System.
But i agree it would be a nice feature, i'll dig into the docs about it.

**Comment by kachnitata** [comment]
It would be nice to also have a way to switch dark theme off, e.g.via a static bool property or method called on the very start of the application. I came across a situation where a user wants to have a light theme but is using a remote desktop where he is not in control of the theme.

**Comment by jukfiuune** [comment]
I'm building an application right now, and im using this to use a dark mode color scheme. I have almost been able to add automatic theme switching, but the problem is that the color scheme wont change because this works one way (obviously the code works only if it detects dark mode), meaning that once i apply the dark color scheme i cant revert the changes. It will be really good if you could add an option for reversing the color changes (i tried to do that but i became frustrated and kinda gave up). Thanks!

**Comment by jukfiuune** [comment]
> it would be nice but the problem is the whole Window Title area and Borders, those are gotten from the System.

Wait i dont understand, what do you mean by that? The titlebar color scheme can be changed with DwmSetWindowAttribute. Or are you talking about something else?

**Comment by BlueMystical** [comment]
OK, lets move this to the [Discussion here](https://github.com/BlueMystical/Dark-Mode-Forms/discussions/38).
